---
name: Setup Shipwright
description: Installs Shipwright Build Controller and dependencies
branding:
  icon: box
  color: green
inputs:
  tekton-version:
    description: Tekton Pipelines version
    required: false
    default: v0.34.1
  shipwright-version:
    description: Shipwright Build Controller version
    required: false
    default: v0.9.0
  setup-registry:
    description: Setup a Container Registry
    required: false
    default: "false"
runs:
  using: composite
  steps:
    # pre-flight checks, making sure the dependencies needed for the upcoming steps are available
    - shell: bash
      run: |
        ./probe.sh
    # deploying the container registry
    - shell: bash
      if: ${{ inputs.setup-registry == 'true' }}
      run: |
        ./install-registry.sh
    # deploying tekton operator and waiting for it to be available
    - shell: bash
      run: |
        TEKTON_VERSION="${{ inputs.tekton-version }}" \
        ./install-tekton.sh
    # deploying shipwright build controller, waiting for the instance to be available
    - shell: bash
      run: |
        SHIPWRIGHT_VERSION="${{ inputs.shipwright-version }}" \
        ./install-shipwright.sh 