---
name: Setup Shipwright
description: Installs Shipwright Build Controller and dependencies
branding:
  icon: box
  color: green
inputs:
  tekton-version:
    description: Tekton Pipelines version
    required: false
    default: v0.34.1
  shipwright-version:
    description: Shipwright Build Controller version
    required: false
    default: v0.9.0
runs:
  using: composite
  steps:
    - shell: bash
      run: ./probe.sh
    - shell: bash
      run: ./install-tekton.sh "${{ inputs.tekton-version }}"
    - shell: bash
      run: ./install-shipwright.sh "${{ inputs.shipwright-version }}"
