---
name: Setup Shipwright
description: Installs Shipwright Build Controller and dependencies
branding:
  color: blue
  icon: anchor 
inputs:
  tekton-version:
    description: Tekton Pipelines version
    required: false
    default: v0.34.1
  shipwright-version:
    description: Shipwright Build Controller version
    required: false
    default: v0.10.0
  setup-registry:
    description: Enable this flag to deploy a Container Registry
    required: false
    default: "false"
runs:
  using: composite
  steps:
    # pre-flight checks, making sure the dependencies needed for the upcoming steps are available
    - shell: bash
      run: |
        ./probe.sh
    # deploying the container registry when input flag is set, waiting for the deployment to reach
    # ready status before proceeding
    - shell: bash
      if: ${{ inputs.setup-registry == 'true' }}
      run: |
        ./install-registry.sh
    # deploying tekton pipline controller and dependencies, waiting for it to reach ready status
    - shell: bash
      run: |
        TEKTON_VERSION="${{ inputs.tekton-version }}" \
        ./install-tekton.sh
    # deploying shipwright build controller, waiting for the instance to be reach ready status
    - shell: bash
      run: |
        SHIPWRIGHT_VERSION="${{ inputs.shipwright-version }}" \
        ./install-shipwright.sh 