---
name: use-action

on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  use-action:
    name: use-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: helm/kind-action@v1.2.0
        with:
          version: v0.14.0
          cluster_name: kind
          wait: 120s

      # self loading the action.yaml definitions, it makes it possible to run the action against the
      # local instance and later on assert the action changes
      - uses: ./
        with:
          setup-registry: true

      - shell: bash
        run: |
          ./assert.sh
